language: c
os: linux
sudo: required

services:
    - docker

script:
    - docker pull ubuntu
    - docker run -i -t -v $PWD:/lvg ubuntu sudo apt-get update -qq && sudo apt-get install -y libglfw3-dev libsdl2-dev libavcodec-dev && cd /lvg && ./build.sh
