language: c

os:
    - linux

compiler:
    - gcc

before_install:
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq && sudo apt-get install -y libglfw3-dev libsdl2-dev libavcodec-dev; fi

script:
    - build.sh
