language: c
os: linux
sudo: required

compiler:
    - gcc

services:
    - docker

script:
    - docker pull ubuntu
    - docker run -i -t -v $PWD:/lvg ubuntu apt-get update -qq && apt-get install -y libglfw3-dev libsdl2-dev libavcodec-dev && cd /lvg && ./build.sh
