language: c
os: linux
sudo: required

compiler:
    - gcc

services:
    - docker

script:
    - docker pull ubuntu:16.04
    - docker run -i -t -v $PWD:/lvg ubuntu:16.04 "apt-get update -qq && apt-get install -qq -y libglfw3-dev libsdl2-dev libavcodec-dev && cd /lvg && ./build.sh"
