language: c
os: linux
sudo: required

compiler:
    - gcc

services:
    - docker

script:
    - docker pull ubuntu:17.04
    - docker run -i -t -v $PWD:/lvg ubuntu:17.04 /lvg/scripts/docker-build.sh
